name: CI

on:
  push:
    branches:
      - master
      - fixes
  pull_request:
    branches:
      - master
      - fixes

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          npm install
          npm run-script build
          npm test
